server:
  port: 8081
  servlet:
    context-parameters:
#  servlet:
#    context-path: /demo
spring:
  datasource:
    test1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root123
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    test2:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/linui?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root123
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml    #配置映射文件
  type-aliases-package: entity   #配置实体类

#xxl-job 配置数据
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8099/xxl-job-admin
    executor:
      appname: functionOne-executor
      address:
      ip:
      port: 9998
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken:

soul:
  http:
    adminUrl: http://localhost:9095  # adminUrl: 为你启动的soul-admin 项目的ip + 端口，注意要加http://
    port: 8081   # port: 你本项目的启动端口
    contextPath: /soul  # contextPath: 为你的这个mvc项目在soul网关的路由前缀
    appName: soul-test  # appName：你的应用名称，不配置的话，会默认取 `spring.application.name` 的值
    full: false    # full: 设置true 代表代理你的整个服务，false表示代理你其中某几个controller

context:
  listener:
    classes: com.hengnan.test.EmailNotifier