server:
  port: 8081
#  servlet:
#    context-path: /demo
spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml    #配置映射文件
  type-aliases-package: entity   #配置实体类